Rebase on upstream (take three)
janestreet/ocamlformat pull request #14
Opened 2023-03-05 12:40 UTC by ccasin

Rebase of all Jane Street stuff (including comprehensions) onto the latest upstream ocamlformat.

@antalsz please look at two things in particular:

1. How I merged your tests into the upstream test refactoring I previously mentioned.
2. I moved `language_extension.{ml,mil}` into the `ocaml-common` directory rather than having copies in each parser.  It looks like they were identical and didn't depend on anything that prevents this, but let me know if there was a reason for how it was.

2023-03-06 19:42 UTC, antalsz commented
Re. #2: `language_extensions.ml{,i}` comes from `ocaml-jst`.  I can't tell if `ocaml-common/` does; if it does, then that's a fine place for `language_extensions.ml{,i}` too.

2023-03-06 21:17 UTC, antalsz requested changes
I went through and grepped the testsuite for `[:` and `[|`, and I'm satisfied that immutable array/comprehension copies of tests occur next to all existing array tests, which is the correctness condition for adding the new tests.  There's one requested change where we should use the immutable array indexing operator, but other than that the two questions for me are hereby addressed!

---

(... `|]`, `:]`.)

2023-03-06 21:17 UTC, antalsz commented on test/passing/tests/index_op.ml
> +let _ = [::].(-8)
```suggestion
let _ = [::].:(-8)
```

(And rerun the test to confirm)

2023-03-07 08:59 UTC, ccasin commented on test/passing/tests/index_op.ml
> +let _ = [::].(-8)
Thanks - fixed.

2023-03-17 15:53 UTC, ceastlund commented
Pushed a newer rebase.

2023-03-17 15:53 UTC, closed without merging